version: "2"

services:
    provider.alias:
        image: alias/sandbox
        ports:
            - "127.0.1.2:80:80"
        command: "sh -c \"(cd provider && nodemon src/app.js)\""
        volumes:
            - ../:/alias
            - ../data/provider.config.json:/config/provider.config.json

        links:
            - redis.provider.alias
            - processor.provider.alias

    processor.provider.alias:
        image: alias/sandbox
        ports:
            - "127.0.1.3:80:80"
        command: "sh -c \"(cd processor/daemon && nodemon src/app.js)\""
        volumes:
            - ../:/alias
        links:
            - client.alias
        environment:
            - ALIAS_PROCESSOR_SRC_BASEPATH=/alias/processor/base/js/src/

    redis.provider.alias:
        image: redis

    client.alias:
        image: alias/sandbox
        ports:
            - "127.0.1.1:80:80"
        command: "sh -c \"(cd client && nodemon src/app.js)\""
        volumes:
            - ../:/alias
            - ../data/client:/client_data
