version: "2"

services:
    authz.gdpr.dev.local:
        image: alias/sandbox
        ports:
            - "127.0.1.2:80:80"
        command: "sh -c \"(cd provider && nodemon src/app.js)\""
        volumes:
            - ../:/alias

        links:
            - redis.authz.gdpr.dev.local
            - processor.authz.gdpr.dev.local

    processor.authz.gdpr.dev.local:
        image: alias/sandbox
        ports:
            - "127.0.1.3:80:80"
        command: "sh -c \"(cd processor/daemon && nodemon app.js)\""
        volumes:
            - ../:/alias
        links:
            - client.gdpr.dev.local


    redis.authz.gdpr.dev.local:
        image: redis

    client.gdpr.dev.local:
        image: alias/sandbox
        ports:
            - "127.0.1.1:80:80"
        command: "sh -c \"(cd client && nodemon src/app.js)\""
        volumes:
            - ../:/alias
            - ../data/client:/client_data
        links:
            - redis.client.gdpr.dev.local

    redis.client.gdpr.dev.local:
        image: redis
