version: "2"

services:
    authz.gdpr.dev.local:
        image: alias/sandbox
        ports:
            - "127.0.1.2:80:8080"
        command: "sh -c \"(cd provider && nodemon src/app.js)\""
        volumes:
            - ../:/alias

    client.gdpr.dev.local:
        image: alias/sandbox
        ports:
            - "127.0.1.1:80:8080"
        command: "sh -c \"(cd client && nodemon src/app.js)\""
        volumes:
            - ../:/alias

    processor.authz.gdpr.dev.local:
        image: alias/sandbox
        ports:
            - "127.0.1.3:80:8080"
        command: "sh -c \"(cd processor/daemon && nodemon app.js)\""
        volumes:
            - ../:/alias

